// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsRQt82eYd8IatoCC2A4Wk5h2qRUN2zMw',
    appId: '1:331643795270:web:269fbcc38ed2b897a35747',
    messagingSenderId: '331643795270',
    projectId: 'shareridewithme-a20fd',
    authDomain: 'shareridewithme-a20fd.firebaseapp.com',
    storageBucket: 'shareridewithme-a20fd.appspot.com',
    measurementId: 'G-F892NZSED7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Wb4PQEYl7CxHKHkrlQTqiAUbU03r_54',
    appId: '1:331643795270:android:ec6a55e7c6bf024fa35747',
    messagingSenderId: '331643795270',
    projectId: 'shareridewithme-a20fd',
    storageBucket: 'shareridewithme-a20fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtksW3Av80KGwuXIAT1R7C0R8c3vHGbUM',
    appId: '1:331643795270:ios:600abf70e8b99cf0a35747',
    messagingSenderId: '331643795270',
    projectId: 'shareridewithme-a20fd',
    storageBucket: 'shareridewithme-a20fd.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtksW3Av80KGwuXIAT1R7C0R8c3vHGbUM',
    appId: '1:331643795270:ios:600abf70e8b99cf0a35747',
    messagingSenderId: '331643795270',
    projectId: 'shareridewithme-a20fd',
    storageBucket: 'shareridewithme-a20fd.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsRQt82eYd8IatoCC2A4Wk5h2qRUN2zMw',
    appId: '1:331643795270:web:9d952b1c657152d7a35747',
    messagingSenderId: '331643795270',
    projectId: 'shareridewithme-a20fd',
    authDomain: 'shareridewithme-a20fd.firebaseapp.com',
    storageBucket: 'shareridewithme-a20fd.appspot.com',
    measurementId: 'G-S0DZ3JLQ52',
  );
}
